name: modora
description: "Modora - Mood Tracker"

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.2.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/

    fonts:
        - family: SUITE
          fonts:
              - asset: assets/fonts/SUITE-Light.otf
                weight: 300
              - asset: assets/fonts/SUITE-Regular.otf
                weight: 400
              - asset: assets/fonts/SUITE-Medium.otf
                weight: 500
              - asset: assets/fonts/SUITE-SemiBold.otf
                weight: 600
              - asset: assets/fonts/SUITE-Bold.otf
                weight: 700
              - asset: assets/fonts/SUITE-ExtraBold.otf
                weight: 800
              - asset: assets/fonts/SUITE-Heavy.otf
                weight: 900
