name: modora
description: "Modora - Mood Tracker"

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.2.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    skeletons: ^0.0.3
    cached_network_image: ^3.3.0
    hooks_riverpod: ^2.4.9
    google_sign_in: ^6.2.1
    sign_in_with_apple: ^5.0.0
    uuid: ^4.2.2
    flutter_web_auth: ^0.5.0
    go_router: ^13.0.0
    firebase_core: ^2.24.2
    firebase_auth: ^4.15.3
    cloud_firestore: ^4.13.6
    firebase_storage: ^11.5.6

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/

    fonts:
        - family: SUITE
          fonts:
              - asset: assets/fonts/SUITE-Light.otf
                weight: 300
              - asset: assets/fonts/SUITE-Regular.otf
                weight: 400
              - asset: assets/fonts/SUITE-Medium.otf
                weight: 500
              - asset: assets/fonts/SUITE-SemiBold.otf
                weight: 600
              - asset: assets/fonts/SUITE-Bold.otf
                weight: 700
              - asset: assets/fonts/SUITE-ExtraBold.otf
                weight: 800
              - asset: assets/fonts/SUITE-Heavy.otf
                weight: 900
