// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa4G4hUtEaFjU7nEQJZ7zvwB7pLfY4bPY',
    appId: '1:723953596318:web:c45e9a44a585e8251e488f',
    messagingSenderId: '723953596318',
    projectId: 'modora',
    authDomain: 'modora.firebaseapp.com',
    storageBucket: 'modora.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpsFaxD6z2KpTQyAtZZliCUfpCs1S8WGM',
    appId: '1:723953596318:android:ac6562ac77d89ff81e488f',
    messagingSenderId: '723953596318',
    projectId: 'modora',
    storageBucket: 'modora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBquUByQ0JYEEIS8k6GE-8oAoYd8FiTeUE',
    appId: '1:723953596318:ios:3d08c749c6c9b2fc1e488f',
    messagingSenderId: '723953596318',
    projectId: 'modora',
    storageBucket: 'modora.appspot.com',
    iosBundleId: 'com.asuracoder.modora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBquUByQ0JYEEIS8k6GE-8oAoYd8FiTeUE',
    appId: '1:723953596318:ios:1743f8f0aca611571e488f',
    messagingSenderId: '723953596318',
    projectId: 'modora',
    storageBucket: 'modora.appspot.com',
    iosBundleId: 'com.asuracoder.modora.RunnerTests',
  );
}
